---
language: php
php:
  - 7.0
  - 7.1
  - nightly

addons:
    postgresql: "9.6"

services:
  - postgresql
  - redis-server

cache:
  directories:
    - node_modules
    - ~/.composer/cache

sudo: false
dist: trusty

install: composer install

before_script:
  - psql -c 'create database portaldev_test;' -U postgres
#  - travis_retry composer install --no-interaction --prefer-source --dev
#  - pip install --user codecov
#  - composer require codeclimate/php-test-reporter --dev

script:
  - php artisan migrate --env=testing --no-interaction
#  - php artisan db:seed --env=testing --no-interaction
#  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit --debug --coverage-clover=build/logs/clover.xml
  - sh ./cache-clean.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter
